{ lib
, rustPlatform
, fetchCrate
}:
rustPlatform.buildRustPackage rec
{
  pname = "form";
  version = "0.12.1";

  src = fetchCrate {
    inherit pname version;
    hash = "sha256-QwiYNmL5oncCw5oEygueyaaudBhydbtYhlpX+hA25zc=";
  };

  cargoHash = "sha256-sVjUyiO9SNCFUZHJLoyWFKM+TQtoQ0xXMwP6//6kbtM=";

  meta = with lib;
    {
      description = "A utility to split autogenerated rust files into human-workable projects with the correct _form_Resources";
      mainProgram = "form";
      homepage = "https://github.com/djmcgill/form";
      license = with licenses; [ mit ];
    };
}
